/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserStatus = "ACTIVE" | "INACTIVE";

export type UserTitle = "ASSISTANT_PROFESSOR" | "ASSOCIATE_PROFESSOR" | "DOCTOR" | "LECTURER" | "LECTURER_DOCTOR" | "PROFESSOR" | "RESEARCH_ASSISTANT" | "RESEARCH_ASSISTANT_DOCTOR";

export type UserType = "ACADEMICIAN" | "POSTDOC" | "STAFF";

export interface PasswordResetToken {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  tokenHash: string;
  userId: string;
}

export interface UserCredential {
  createdAt: Generated<Timestamp>;
  failedLoginCount: Generated<number>;
  id: Generated<string>;
  lastLoginAt: Timestamp | null;
  lockedUntil: Timestamp | null;
  passwordChangedAt: Timestamp;
  passwordHash: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  email: string;
  iban: string | null;
  id: Generated<string>;
  name: string;
  status: Generated<UserStatus>;
  surname: string;
  title: UserTitle | null;
  updatedAt: Generated<Timestamp>;
  userType: UserType;
}

export interface DB {
  passwordResetTokens: PasswordResetToken;
  userCredentials: UserCredential;
  users: User;
}
